(function () {
  'use strict';

  const CREDIT_LINE = '# Generated by zMenu Menu Editor';

  function escapeHtml(value) {
    return String(value == null ? '' : value)
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;');
  }

  function formatYaml(raw, options) {
    let lines = String(raw || '').replace(/\r\n?/g, '\n').split('\n');
    const hasCredit = lines.some(function (line) { return line.trim() === CREDIT_LINE; });
    if (!hasCredit) lines.unshift(CREDIT_LINE);
    if (!options.comments) {
      lines = lines.filter(function (line) { return line.trim() === CREDIT_LINE || !/^\s*#/.test(line); });
    }
    if (!options.docLinks) {
      lines = lines.filter(function (line) { return line.trim() === CREDIT_LINE || !/https?:\/\//i.test(line); });
    }
    if (!options.spacing) {
      lines = lines.filter(function (line) { return line.trim() !== ''; });
    }
    return lines.join('\n').replace(/\n+$/, '') + '\n';
  }

  function highlightLine(line) {
    if (/^\s*#/.test(line)) return '<span class="yh-comment">' + escapeHtml(line) + '</span>';
    const match = line.match(/^(\s*)(-\s+)?([A-Za-z0-9_.-]+)(:)(.*)$/);
    if (!match) {
      return escapeHtml(line).replace(/^(\s*)(-\s+)/, '$1<span class="yh-dash">$2</span>');
    }
    const value = escapeHtml(match[5]).split(/("(?:\\.|[^"\\])*"|'[^']*')/g).map(function (part, index) {
      if (index % 2 === 1) return '<span class="yh-string">' + part + '</span>';
      return part.replace(/\b(true|false|yes|no)\b/gi, '<span class="yh-bool">$1</span>')
        .replace(/\b(null|~)\b/g, '<span class="yh-null">$1</span>')
        .replace(/(^|[\s\[,])(-?\d+(?:\.\d+)?)(?=$|[\s,\]])/g, '$1<span class="yh-number">$2</span>');
    }).join('');
    return escapeHtml(match[1])
      + (match[2] ? '<span class="yh-dash">' + escapeHtml(match[2]) + '</span>' : '')
      + '<span class="yh-key">' + escapeHtml(match[3]) + '</span>'
      + '<span class="yh-colon">' + match[4] + '</span>'
      + value;
  }

  function highlightYaml(value) {
    const text = String(value || '');
    const trailingNewline = text.endsWith('\n');
    const lines = text.replace(/\n$/, '').split('\n');
    return lines.map(highlightLine).join('\n') + (trailingNewline ? '\n' : '');
  }

  function copyText(value) {
    if (navigator.clipboard && window.isSecureContext) return navigator.clipboard.writeText(value);
    const helper = document.createElement('textarea');
    helper.value = value;
    helper.style.position = 'fixed';
    helper.style.opacity = '0';
    document.body.appendChild(helper);
    helper.focus();
    helper.select();
    let copied = false;
    try { copied = document.execCommand('copy'); } catch (error) { copied = false; }
    helper.remove();
    return copied ? Promise.resolve() : Promise.reject(new Error('Copy failed'));
  }

  function openYamlPreview(payload) {
    const builder = document.getElementById('builder') || document.body;
    const oldOverlay = builder.querySelector('.bv2-yaml-preview-overlay');
    if (oldOverlay) oldOverlay.remove();
    const rawYaml = String(payload && payload.yaml || '');
    const overlay = document.createElement('div');
    overlay.className = 'bv2-modal-overlay bv2-yaml-preview-overlay';
    overlay.innerHTML = '<div class="bv2-modal bv2-modal--yaml" role="dialog" aria-modal="true" aria-label="Inventory YAML preview">'
      + '<div class="bv2-modal__header"><span>YAML Preview</span><button type="button" class="bv2-modal__close" aria-label="Close"><i class="bi bi-x-lg" aria-hidden="true"></i></button></div>'
      + '<div class="bv2-yaml-modal__toolbar">'
      + '<label class="bv2-yaml-modal__opt"><input type="checkbox" data-yaml-option="comments" checked><span>Comments</span></label>'
      + '<label class="bv2-yaml-modal__opt"><input type="checkbox" data-yaml-option="spacing" checked><span>Spacing</span></label>'
      + '<label class="bv2-yaml-modal__opt"><input type="checkbox" data-yaml-option="docLinks" checked><span>Doc links</span></label>'
      + '<label class="bv2-yaml-modal__opt bv2-yaml-modal__opt--select"><span>Detail</span><select data-yaml-option="detail"><option value="minimal">Minimal</option><option value="full" selected>Full</option></select></label>'
      + '<span class="bv2-yaml-modal__toolbar-hint">Applies to preview + download. The credit line is always kept.</span>'
      + '</div>'
      + '<div class="bv2-modal__body"><div class="bv2-yaml-editor"><div class="bv2-yaml-editor__gutter" aria-hidden="true"></div><div class="bv2-yaml-editor__main"><pre class="bv2-yaml-editor__highlight"></pre><textarea class="bv2-yaml-editor__textarea" readonly spellcheck="false" aria-label="YAML preview"></textarea></div></div></div>'
      + '<div class="bv2-modal__footer"><button type="button" class="bv2-btn bv2-yaml-close">Close</button><button type="button" class="bv2-btn bv2-btn--primary bv2-yaml-copy"><i class="bi bi-copy" aria-hidden="true"></i> Copy</button></div>'
      + '</div>';
    builder.appendChild(overlay);

    const modal = overlay.querySelector('.bv2-modal');
    const textarea = overlay.querySelector('.bv2-yaml-editor__textarea');
    const highlight = overlay.querySelector('.bv2-yaml-editor__highlight');
    const gutter = overlay.querySelector('.bv2-yaml-editor__gutter');
    const copyButton = overlay.querySelector('.bv2-yaml-copy');
    const options = { comments: true, spacing: true, docLinks: true, detail: 'full' };
    window.ZMenuEditorYamlOptions = options;

    function update() {
      const text = formatYaml(rawYaml, options);
      const lines = text.replace(/\n$/, '').split('\n');
      textarea.value = text;
      highlight.innerHTML = highlightYaml(text);
      gutter.textContent = lines.map(function (_, index) { return String(index + 1); }).join('\n');
      textarea.scrollTop = 0;
      textarea.scrollLeft = 0;
      highlight.scrollTop = 0;
      highlight.scrollLeft = 0;
      gutter.scrollTop = 0;
    }

    function close() {
      document.removeEventListener('keydown', onKeydown);
      overlay.remove();
    }

    function onKeydown(event) {
      if (event.key === 'Escape') close();
    }

    overlay.querySelectorAll('[data-yaml-option]').forEach(function (control) {
      control.addEventListener('change', function () {
        const key = control.dataset.yamlOption;
        options[key] = control.type === 'checkbox' ? control.checked : control.value;
        update();
      });
    });
    textarea.addEventListener('scroll', function () {
      highlight.scrollTop = textarea.scrollTop;
      highlight.scrollLeft = textarea.scrollLeft;
      gutter.scrollTop = textarea.scrollTop;
    });
    overlay.querySelector('.bv2-modal__close').addEventListener('click', close);
    overlay.querySelector('.bv2-yaml-close').addEventListener('click', close);
    overlay.addEventListener('mousedown', function (event) { if (event.target === overlay) close(); });
    copyButton.addEventListener('click', function () {
      copyText(textarea.value).then(function () {
        copyButton.classList.add('is-copied');
        copyButton.innerHTML = '<i class="bi bi-check2" aria-hidden="true"></i> Copied';
        window.setTimeout(function () {
          if (!document.body.contains(copyButton)) return;
          copyButton.classList.remove('is-copied');
          copyButton.innerHTML = '<i class="bi bi-copy" aria-hidden="true"></i> Copy';
        }, 1200);
      }).catch(function () {
        copyButton.innerHTML = '<i class="bi bi-exclamation-triangle" aria-hidden="true"></i> Copy failed';
      });
    });
    document.addEventListener('keydown', onKeydown);
    update();
    requestAnimationFrame(function () { modal.querySelector('.bv2-yaml-close').focus(); });
  }

  window.ZMenuEditorFormatYaml = formatYaml;
  window.ZMenuEditorOpenYamlPreview = openYamlPreview;
})();
